### ISSUE TITLE
Collect together OA Week 22 content links

### ISSUE THREAD

**Issue by mrchristian** [petermr/semanticClimate#12]
OA Week - https://github.com/petermr/semanticClimate/blob/pmr1/ipcc/ar6/OA_WEEK_2022.md

semanticClimate - https://github.com/petermr/semanticClimate/blob/main/README.md

Instructions CoLab - https://github.com/petermr/semanticClimate/tree/main/outreach/climate_knowledge_hunt_hackathon/Hackathon_Notebook

Video about hakathon - Post-Hackthon Pitch to SDG Accelerator (12 min.): https://youtu.be/0MGXic-uEQY

Other events page - https://github.com/petermr/semanticClimate/blob/main/events.md

**Comment by petermr** [comment]
event is well past
