### ISSUE TITLE
OA Week TDL - To do list (Just some suggestions)

### ISSUE THREAD

**Issue by mrchristian** [petermr/semanticClimate#13]
- Guide for the current workflow
- Guide for making a dictionary
- List IPCC Report chapters and have a way to organise volunteers
- Invitation and instructions for Chapter Champions
- Invitation and instructions for volunteers
- Coordinate on recruitment
- Organisers test workflow and give feedback
- Translation of key parts of reports into  non-EN language
- Translation of instructions (notebooks, these pages)
- Setup documentation and knowledge management process an infra
- Form organising team and assign roles, and tasks, infra
-

**Comment by petermr** [comment]
event past
